language: ruby

rvm:
  - "2.4.3"
  - "2.5.1"
  - "2.6.5"
  - "2.7.0"

before_install: gem install bundler

cache: bundler

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle
